---
- name: Query Okta for users inactive for 90 days
  hosts: localhost
  tasks:
    - name: List Okta Users
      okta_users:
        action: list
        organization: leoconnect
        api_key: here is api key
      register: okta_users
    - name: Print Users
      debug:
        msg: "{{ okta_users.json }}"
